train_path: "./data/train.txt"
test_path: "./data/test.txt"
validation_path: "./data/validation.txt"
pred_word2vec_path: "./data/wiki_word2vec_50.bin"
word2id_path: "./data/word2id"
word2vec_path: "./data/word2vec"
tensorboard_path: "./tensorboard"
model_save_path: "./modelDict/model.pth"
embedding_dim: 50
hidden_dim: 50
lr: 0.001
LSTM_layers: 3
drop_prob: 0.5
seed: 0
batch_first: True
bidirectional: False
batch_size: 16
shuffle: True
num_workers: 0
epochs: 6
step_size: 2
lr_gamma: 0.1
